# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CleanArchitectureMovie' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CleanArchitectureMovie

  inhibit_all_warnings!

  pod 'RxSwift', '~> 5'
	pod 'RxCocoa', '~> 5'
	pod 'Moya/RxSwift', '~> 14.0'
  pod 'Then'
  pod 'CocoaLumberjack/Swift'
	pod 'Kingfisher', '~> 5.0'
	pod 'SnapKit', '~> 5.0.0'
end
